name: Get Migration

on:
    workflow_dispatch:

jobs:
  post-request:
    runs-on: ubuntu-latest

    steps:
      - name: Install httpie
        run: |
          sudo apt-get update && sudo apt-get install -y httpie
      
      - name: Make Post Request
        run: |
          http --ignore-stdin --form POST https://teknoexpo.azurewebsites.net/utils/get-migrate private_key='${{ secrets.PRIVATE_KEY }}'
