name: Migration

on:
  workflow_dispatch: {}

jobs:
  post-request:
    runs-on: ubuntu-latest

    steps:
      - name: Perform POST Request
        run: |
          $(curl --location --request POST 'https://teknoexpo.azurewebsites.net/utils/migrate' --form 'private_key="${{ secrets.PRIVATE_KEY }}"')
