name: Migration

on:
  workflow_dispatch: {}

jobs:
  post-request:
    runs-on: ubuntu-latest

    steps:
      - name: Make POST request
        run: |
          sudo apt-get update && sudo apt-get install -y httpie
          http --ignore-stdin --form POST https://teknoexpo.azurewebsites.net/utils/migrate private_key='${{ secrets.PRIVATE_KEY }}'
