name: Migration

on:
  workflow_dispatch: {}

jobs:
  post-request:
    runs-on: ubuntu-latest

    steps:
      - name: Perform POST Request
        uses: fjogeleit/http-request-action@v1
        with:
          method: POST
          url: https://teknoexpo.azurewebsites.net/utils/migrate
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"private_key": "${{ secrets.PRIVATE_KEY }}"}'
