name: Migration

on:
  workflow_dispatch: {}

jobs:
  post-request:
    runs-on: ubuntu-latest

    steps:
      - name: Perform POST Request
        uses: http-request/action@v1
        with:
          method: POST
          url: https://teknoexpo.azurewebsites.net/utils/migrate
          headers: |
            Content-Type: application/json
          data: '{"private_key": "${{ secrets.PRIVATE_KEY }}"}'
